
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = ["github.com/onsi/ginkgo/ginkgo"]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/localip"

[[constraint]]
  name = "github.com/Microsoft/hcsshim"
  source = "github.com/greenhouse-org/hcsshim"
  branch = "extra-endpoint-info"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-ps"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  revision = "34170989dc28be797f7078f88df156a474d7fd11"

[[constraint]]
  name = "github.com/opencontainers/runtime-tools"
  revision = "e29f3ca4eb806a582ee1a1864c7b0563bd64c19b"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  branch = "master"
  name = "golang.org/x/text"

[[constraint]]
  branch = "master"
  name = "github.com/hectane/go-acl"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/filelock"

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/silk"
